# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressesapp', '0002_remove_person_mobilephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Test'),
        ),
    ]
