# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-05 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('array', jsonfield.fields.JSONField()),
                ('ndim', models.IntegerField(default=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieRated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('movieindx', models.IntegerField(default=-1)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', jsonfield.fields.JSONField()),
                ('arrayratedmoviesindxs', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=1000)),
                ('lastrecs', jsonfield.fields.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movierated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedmovies', to='books_recsys_app.UserProfile'),
        ),
    ]
